### ISSUE TITLE
Click navigation goes nuts when looping

### ISSUE THREAD

**Issue by mdeboer** [odahcam/owlcarousel-sync-plugin#6]
Browsing the interwebs I found this neat little trick to get looping to work correctly. The trick is to get the relative index instead of the absolute index using `carousel.relative()`.

`carousel.relative($(this).index())`

I'll have a go at it and do some tests!

**Comment by odahcam** [comment]
I'm studing some forms to do this. One of them is to create a Click Navigation plugin, in the same model of @daviddeutsch Linked plugin.

Once the click slides the thumbnail carousel to the slide **x**, the Linked carousel will sync in the slide **x** too, giving the impression of a thumbnail navigation, where the navigation works in the thumbs carousel and is synced with the main carousel.

Once we hace the owlCarousel plugin structure, we can take the relative index easily.

What you think?

**Comment by odahcam** [comment]
Plugin for click navigation with **loop:true**: https://github.com/odahcam/OwlCarousel2/blob/develop/src/js/owl.mousenav.js
